---
elasticsearch_key_url: 'https://packages.elastic.co/GPG-KEY-elasticsearch'
elasticsearch_repo_url: 'deb http://packages.elastic.co/elasticsearch/2.x/debian stable main'

elasticsearch_heap_size: '512m'
elasticsearch_max_open_files: '65535'
elasticsearch_cluster_name: 'test'
elasticsearch_number_of_shards: 4
elasticsearch_number_of_replicas: 0
elasticsearch_network_host: 0
