---
- name: Add ElasticSearch apt key
  apt_key: url=https://packages.elasticsearch.org/GPG-KEY-elasticsearch state=present

- name: Add ElasticSearch repository
  apt_repository: repo='deb http://packages.elasticsearch.org/elasticsearch/1.4/debian stable main' state=present

- name: Install ElasticSearch
  apt: name={{ item }} state=latest update_cache=yes cache_valid_time=3600
  with_items:
    - elasticsearch

- name: Add ElasticSearch default file
  template: src=elasticsearch.defaults dest=/etc/default/elasticsearch
  notify: restart elasticsearch

- name: Add ElasticSearch config file
  template: src=elasticsearch.yml dest=/etc/elasticsearch/elasticsearch.yml
  notify: restart elasticsearch

- name: Ensure ElasticSearch starts on boot
  service: name=elasticsearch enabled=yes

- name: Start Elasticsearch
  service: name=elasticsearch state=started

